/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package interfazGrafica;
import facturacion.elementos.Factura;
import facturacion.elementos.Cliente;
import facturacion.elementos.Pedido;
import facturacion.elementos.Helado;
import java.util.Locale;
import java.text.SimpleDateFormat;

/**
 *
 * @author elian
 */
public class VentanaFactura extends javax.swing.JDialog {
    private Factura factura;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaFactura.class.getName());

    /**
     * Creates new form VentanaFactura
     */
    public VentanaFactura(java.awt.Frame parent, boolean modal, Factura factura) {
        super(parent, modal);
        this.factura = factura; // <-- Guarda la factura
        initComponents();

        this.setLocationRelativeTo(parent); // Centra la ventana
        mostrarResumenEnTextArea(); // Llena el área de texto
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFact = new javax.swing.JScrollPane();
        textFact = new javax.swing.JTextArea();
        bttCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        textFact.setEditable(false);
        textFact.setColumns(20);
        textFact.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        textFact.setRows(5);
        panelFact.setViewportView(textFact);

        bttCerrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bttCerrar.setText("CERRAR");
        bttCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelFact)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(372, Short.MAX_VALUE)
                .addComponent(bttCerrar)
                .addGap(330, 330, 330))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelFact, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bttCerrar)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_bttCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                VentanaFactura dialog = new VentanaFactura(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttCerrar;
    private javax.swing.JScrollPane panelFact;
    private javax.swing.JTextArea textFact;
    // End of variables declaration//GEN-END:variables

    private void mostrarResumenEnTextArea() {
        // ASUNCIÓN: Tu JTextArea se llama 'textFact'

        if (this.factura == null) {
            textFact.setText("ERROR: No se recibió ninguna factura.");
            return;
        }

        StringBuilder sb = new StringBuilder();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");

        // --- ENCABEZADO ---
        sb.append("========================================\n");
        sb.append("         HELADERÍA - FACTURA\n");
        sb.append("========================================\n\n");
        sb.append("Factura ID:   ").append(factura.getIdFactura()).append("\n");
        sb.append("Fecha:        ").append(sdf.format(factura.getFechaEmision())).append("\n\n");

        // --- DATOS DEL CLIENTE ---
        sb.append("--- DATOS DEL CLIENTE ---\n");
        Cliente c = factura.getCliente();
        if (c != null) {
            sb.append("Cédula:   ").append(c.getCedula()).append("\n");
            sb.append("Nombre:   ").append(c.getNombre()).append("\n\n");
        } else {
            sb.append("Cliente no especificado.\n\n");
        }

        // --- DETALLE DEL PEDIDO ---
        sb.append("--- DETALLE DEL PEDIDO ---\n");
        sb.append(String.format(Locale.US, "%-8s %-40s %-12s %s\n",
                "Cant.",
                "Sabor",
                "Recipiente",
                "Total"));
        sb.append("----------------------------------------------------------\n");

        // ******** AQUÍ ESTÁ LA CORRECCIÓN ********
        // Obtenemos el pedido
        Pedido p = factura.getPedido();

        // Verificamos si el pedido 'p' o su lista de helados son nulos
        if (p == null || p.getHelados() == null) {
            sb.append("Error: El detalle del pedido no está disponible.\n");
        } else {
            // Si no son nulos, los mostramos
            for (Helado h : p.getHelados()) {
                double precioHelado = h.getPrecio();
                sb.append(String.format(Locale.US, "%-8s %-40s %-12s $%.2f\n",
                        "1",
                        h.getSaborHelado().toString(), // <-- Aquí añades el sabor
                        h.getRecipiente().getTipo().toString(),
                        precioHelado));
            }
        }
        sb.append("\n");
        // ******** FIN DE LA CORRECCIÓN ********

        // --- TOTALES ---
        sb.append("--- TOTALES ---\n");
        double iva = factura.getImpuestoIVA();
        double total = factura.getTotal();
        double subtotal = total - iva;
        double cambio = factura.getCambio();

        sb.append(String.format(Locale.US, "Subtotal:      $%.2f\n", subtotal));
        sb.append(String.format(Locale.US, "IVA (15%%):     $%.2f\n", iva));
        sb.append("----------------------------------------\n");
        sb.append(String.format(Locale.US, "TOTAL A PAGAR: $%.2f\n\n", total));
        sb.append(String.format(Locale.US, "CAMBIO: $%.2f\n\n", cambio));

        sb.append("       ¡Gracias por su compra!\n");

        // Asigna el texto al JTextArea 
        textFact.setText(sb.toString());
    }
}
