/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfazGrafica;

import facturacion.elementos.Cliente;
import facturacion.elementos.Helado;
import facturacion.elementos.Pedido;
import facturacion.elementos.enumeraciones.SaborHelado;
import facturacion.elementos.enumeraciones.TipoRecipiente;
import facturacion.gestores.GestorFactura;
import facturacion.gestores.interfaces.*;
import java.awt.Color;
import java.awt.Insets;
import javax.swing.JFrame;
import java.util.ArrayList;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

import facturacion.elementos.Promocion;
import facturacion.elementos.BolaHelado;
import facturacion.elementos.Factura;
import facturacion.elementos.ReporteCierreCaja;
import java.awt.Component;
import java.awt.Font;
import java.util.Map;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author emili
 */
public class VentanaCajero extends javax.swing.JFrame {
    Color materialBlue = new Color(66, 133, 244);
    Color softPink = new Color(208, 60, 62);
    Color softGreen = new Color(73, 159, 44);
    private LoginVentana loginDeOrigen;
    private IGestorStockCajero gestorStock;
    private IGestorPedido gestorPedido;
    private IGestorCaja gestorCaja;
    private IGestorPromocionCajero gestorPromocion;
    private IGestorClienteCajero gestorCliente;
    private IGestorFacturaCajero gestorFactura;
    private int numBolas = 0;
    private Pedido pedidoActualParaFacturar;
    private int intentosCierreCaja = 3;
    private double totalCajaCalculado = -1.0;
    
    /**
     * Creates new form VentanaCajero
     * @param login
     */
    public VentanaCajero(IGestorStockCajero gStock, IGestorPedido gPedido, IGestorCaja gCaja, IGestorPromocionCajero gPromocion, IGestorClienteCajero gCliente, IGestorFacturaCajero gFactura, LoginVentana login) {
        this.loginDeOrigen = login;
        this.gestorStock = gStock;
        this.gestorPedido = gPedido;
        this.gestorCaja = gCaja;
        this.gestorPromocion = gPromocion;
        this.gestorCliente = gCliente;
        this.gestorFactura = gFactura;
        
        //Iniciando al persist de pedidos y factura para mostrar el contador de pedidos y los pedidos ya facturados adecuadamente
        facturacion.persistencia.PedidoPersist.buscarPedido(-1);
        facturacion.persistencia.FacturaPersist.buscarFactura(-1);
        
       // Estilo de la Ventnana Tabbed
        Color tabBgColor = UIManager.getColor("TabbedPane.background");
        UIManager.put("TabbedPane.selected", tabBgColor);
        UIManager.put("TabbedPane.selectHighlight", tabBgColor);
        UIManager.put("TabbedPane.light", tabBgColor);
        UIManager.put("TabbedPane.contentBorderInsets", new Insets(0, 0, 0, 0));
        UIManager.put("TabbedPane.drawFocusIndicator", false);
        
        initComponents();
        agregarListenersDePlaceholder(); 
        radConsumidorFinalActionPerformed(null);
        this.gestorPedido.iniciarNuevoPedido();

        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        //Listener que volvera al login cuando se cierre esta ventana
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                //Si hay un pedido en curso, cancelarlo y devolver stock
                gestorPedido.cancelarPedidoActual();
                //Volver a mostrar Login
                loginDeOrigen.setVisible(true);
                //Cerrar Cajero
                dispose();
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoNumBolas = new javax.swing.ButtonGroup();
        buttonSelecCliente = new javax.swing.ButtonGroup();
        tabCajero = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        botonRegistrarPedido = new javax.swing.JButton();
        botonRegistrarPedido.setBackground(softGreen);
        botonRegistrarPedido.setForeground(Color.WHITE);
        botonRegistrarPedido.setOpaque(true);
        botonRegistrarPedido.setBorderPainted(false);
        botonRegistrarPedido.setContentAreaFilled(true);
        jPanel5 = new javax.swing.JPanel();
        botonAgregarHelado = new javax.swing.JButton();
        botonAgregarHelado.setBackground(materialBlue);
        botonAgregarHelado.setForeground(Color.WHITE);
        botonAgregarHelado.setOpaque(true);
        botonAgregarHelado.setBorderPainted(false);
        botonAgregarHelado.setContentAreaFilled(true);
        opcionUna = new javax.swing.JRadioButton();
        opcionUna.setBackground(Color.WHITE);
        opcionUna.setForeground(Color.BLACK);
        opcionUna.setOpaque(true);
        opcionUna.setContentAreaFilled(false);
        opcionUna.setBorderPainted(false);
        opcionDos = new javax.swing.JRadioButton();
        opcionDos.setBackground(Color.WHITE);
        opcionDos.setForeground(Color.BLACK);
        opcionDos.setOpaque(true);
        opcionDos.setContentAreaFilled(false);
        opcionDos.setBorderPainted(false);
        opcionTres = new javax.swing.JRadioButton();
        opcionTres.setBackground(Color.WHITE);
        opcionTres.setForeground(Color.BLACK);
        opcionTres.setOpaque(true);
        opcionTres.setContentAreaFilled(false);
        opcionTres.setBorderPainted(false);
        jLabel1 = new javax.swing.JLabel();
        sabor1Op = new javax.swing.JComboBox<>();
        sabor1Op.setBackground(Color.WHITE);
        sabor1Op.setForeground(Color.BLACK);
        sabor1Op.setOpaque(true);
        sabor1Op.setBorder(null);
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        sabor2Op = new javax.swing.JComboBox<>();
        sabor2Op.setBackground(Color.WHITE);
        sabor2Op.setForeground(Color.BLACK);
        sabor2Op.setOpaque(true);
        sabor2Op.setBorder(null);
        sabor3Op = new javax.swing.JComboBox<>();
        sabor3Op.setBackground(Color.WHITE);
        sabor3Op.setForeground(Color.BLACK);
        sabor3Op.setOpaque(true);
        sabor3Op.setBorder(null);
        jLabel5 = new javax.swing.JLabel();
        comboRecipiente = new javax.swing.JComboBox<>();
        comboRecipiente.setBackground(Color.WHITE);
        comboRecipiente.setForeground(Color.BLACK);
        comboRecipiente.setOpaque(true);
        comboRecipiente.setBorder(null);
        jLabel6 = new javax.swing.JLabel();
        labelNumPedido = new javax.swing.JLabel();
        labelNumPedido.setText(String.format("# %d", Pedido.getSiguienteNumPedido()));
        jLabel9 = new javax.swing.JLabel();
        comboHelados = new javax.swing.JComboBox<>();
        comboHelados.setBackground(Color.WHITE);
        comboHelados.setForeground(Color.BLACK);
        comboHelados.setOpaque(true);
        comboHelados.setBorder(null);
        botonEliminarHelado = new javax.swing.JButton();
        botonEliminarHelado.setBackground(softPink);
        botonEliminarHelado.setForeground(Color.WHITE);
        botonEliminarHelado.setOpaque(true);
        botonEliminarHelado.setBorderPainted(false);
        botonEliminarHelado.setContentAreaFilled(true);
        PanelFactura = new javax.swing.JPanel();
        titleFact = new javax.swing.JPanel();
        panelDatosCliente = new javax.swing.JPanel();
        radConsumidorFinal = new javax.swing.JRadioButton();
        radIngresarDatos = new javax.swing.JRadioButton();
        idCliente = new javax.swing.JLabel();
        idCampo = new javax.swing.JTextField();
        nombresCliente = new javax.swing.JLabel();
        nomCamp = new javax.swing.JTextField();
        direccionCliente = new javax.swing.JLabel();
        dirCamp = new javax.swing.JTextField();
        emailCliente = new javax.swing.JLabel();
        emailCamp = new javax.swing.JTextField();
        telfClient = new javax.swing.JLabel();
        telefonoCamp = new javax.swing.JTextField();
        bttBuscarCliente = new javax.swing.JButton();
        botAniadirCli = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        bttCargPed = new javax.swing.JButton();
        panelTab = new javax.swing.JScrollPane();
        tablaPedido = new javax.swing.JTable();
        textID = new javax.swing.JLabel();
        idCamp = new javax.swing.JTextField();
        panelResumFact = new javax.swing.JPanel();
        apliProm = new javax.swing.JCheckBox();
        laSubtotal = new javax.swing.JLabel();
        lbDescuento = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lbIVA = new javax.swing.JLabel();
        lbTotal = new javax.swing.JLabel();
        valSubtotal = new javax.swing.JLabel();
        valDescuento = new javax.swing.JLabel();
        valIVA = new javax.swing.JLabel();
        valTotal = new javax.swing.JLabel();
        botCalTotal = new javax.swing.JButton();
        botGenFact = new javax.swing.JButton();
        fieldPago = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        labelTotalFactura = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        campoTotalEfectivo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        botonCerrarCaja = new javax.swing.JButton();
        botonCerrarCaja.setBackground(softGreen);
        botonCerrarCaja.setForeground(Color.WHITE);
        botonCerrarCaja.setOpaque(true);
        botonCerrarCaja.setBorderPainted(false);
        botonCerrarCaja.setContentAreaFilled(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        tabCajero.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(5580, 365));

        botonRegistrarPedido.setBackground(new java.awt.Color(73, 159, 44));
        botonRegistrarPedido.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonRegistrarPedido.setForeground(new java.awt.Color(255, 255, 255));
        botonRegistrarPedido.setText("REGISTRAR PEDIDO");
        botonRegistrarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarPedidoActionPerformed(evt);
            }
        });

        botonAgregarHelado.setText("Agregar Helado");
        botonAgregarHelado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarHeladoActionPerformed(evt);
            }
        });

        grupoNumBolas.add(opcionUna);
        opcionUna.setText("1");
        opcionUna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionNumBolasActionPerformed(evt);
            }
        });

        grupoNumBolas.add(opcionDos);
        opcionDos.setText("2");
        opcionDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionNumBolasActionPerformed(evt);
            }
        });

        grupoNumBolas.add(opcionTres);
        opcionTres.setText("3");
        opcionTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionNumBolasActionPerformed(evt);
            }
        });

        jLabel1.setText("Número de Bolas de Helado");

        sabor1Op.setModel(new javax.swing.DefaultComboBoxModel<>(SaborHelado.values()));
        sabor1Op.setBorder(null);
        sabor1Op.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sabor1OpActionPerformed(evt);
            }
        });

        jLabel2.setText("Sabor 1");

        jLabel3.setText("Sabor 2");

        jLabel4.setText("Sabor 3");

        sabor2Op.setModel(new javax.swing.DefaultComboBoxModel<>(SaborHelado.values()));
        sabor2Op.setBorder(null);
        sabor2Op.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sabor2OpActionPerformed(evt);
            }
        });

        sabor3Op.setModel(new javax.swing.DefaultComboBoxModel<>(SaborHelado.values()));
        sabor3Op.setBorder(null);

        jLabel5.setText("Recipiente");

        comboRecipiente.setModel(new javax.swing.DefaultComboBoxModel<>(TipoRecipiente.values()));
        comboRecipiente.setBorder(null);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(botonAgregarHelado, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(82, 82, 82))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(opcionUna)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(opcionDos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(opcionTres))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(sabor1Op, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(comboRecipiente, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sabor3Op, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(sabor2Op, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opcionUna)
                    .addComponent(opcionDos)
                    .addComponent(opcionTres))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sabor1Op, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboRecipiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(4, 4, 4)
                .addComponent(sabor2Op, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sabor3Op, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(botonAgregarHelado, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        jLabel6.setBackground(new java.awt.Color(255, 255, 204));
        jLabel6.setText("Número de Pedido");

        labelNumPedido.setBackground(new java.awt.Color(204, 255, 204));
        labelNumPedido.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        labelNumPedido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel9.setText("¿Eliminar Helados?");

        comboHelados.setModel(new javax.swing.DefaultComboBoxModel<>());
        comboHelados.setBorder(null);
        comboHelados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboHeladosActionPerformed(evt);
            }
        });

        botonEliminarHelado.setText("Eliminar Helado");
        botonEliminarHelado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarHeladoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(32, 32, 32))
                                    .addComponent(labelNumPedido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(144, 144, 144))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botonEliminarHelado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(comboHelados, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(41, 41, 41))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(botonRegistrarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelNumPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboHelados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonEliminarHelado)
                        .addGap(27, 27, 27)
                        .addComponent(botonRegistrarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        tabCajero.addTab("Crear un Pedido", jPanel1);

        PanelFactura.setBackground(new java.awt.Color(255, 255, 255));
        PanelFactura.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        titleFact.setBackground(new java.awt.Color(255, 255, 255));
        titleFact.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FACTURA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Candara", 0, 24))); // NOI18N

        javax.swing.GroupLayout titleFactLayout = new javax.swing.GroupLayout(titleFact);
        titleFact.setLayout(titleFactLayout);
        titleFactLayout.setHorizontalGroup(
            titleFactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 109, Short.MAX_VALUE)
        );
        titleFactLayout.setVerticalGroup(
            titleFactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panelDatosCliente.setBackground(new java.awt.Color(255, 255, 204));
        panelDatosCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "1. Datos del cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 14))); // NOI18N

        buttonSelecCliente.add(radConsumidorFinal);
        radConsumidorFinal.setSelected(true);
        radConsumidorFinal.setText("Consumidor Final");
        radConsumidorFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radConsumidorFinalActionPerformed(evt);
            }
        });

        buttonSelecCliente.add(radIngresarDatos);
        radIngresarDatos.setText("Datos del Cliente");
        radIngresarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radIngresarDatosActionPerformed(evt);
            }
        });

        idCliente.setText("Cédula:*");

        idCampo.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        idCampo.setForeground(new java.awt.Color(204, 204, 204));
        idCampo.setText("Ej. 1315267891");
        idCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idCampoActionPerformed(evt);
            }
        });

        nombresCliente.setText("Nombres:*");

        nomCamp.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        nomCamp.setForeground(new java.awt.Color(204, 204, 204));
        nomCamp.setText("Ej. Maria Lopez");

        direccionCliente.setText("Dirección:*");

        dirCamp.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        dirCamp.setForeground(new java.awt.Color(204, 204, 204));
        dirCamp.setText("Ej. Av. Amazonas OE1");
        dirCamp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dirCampActionPerformed(evt);
            }
        });

        emailCliente.setText("Email:*");

        emailCamp.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        emailCamp.setForeground(new java.awt.Color(204, 204, 204));
        emailCamp.setText("Ej. marialope1@gmail.com");
        emailCamp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailCampActionPerformed(evt);
            }
        });

        telfClient.setText("Teléfono:*");
        telfClient.setToolTipText("");

        telefonoCamp.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        telefonoCamp.setForeground(new java.awt.Color(204, 204, 204));
        telefonoCamp.setText("Ej. 0965742142");
        telefonoCamp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonoCampActionPerformed(evt);
            }
        });

        bttBuscarCliente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bttBuscarCliente.setText("BUSCAR");
        bttBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttBuscarClienteActionPerformed(evt);
            }
        });

        botAniadirCli.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botAniadirCli.setText(" AÑADIR CLIENTE");
        botAniadirCli.setEnabled(false);
        botAniadirCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botAniadirCliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDatosClienteLayout = new javax.swing.GroupLayout(panelDatosCliente);
        panelDatosCliente.setLayout(panelDatosClienteLayout);
        panelDatosClienteLayout.setHorizontalGroup(
            panelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDatosClienteLayout.createSequentialGroup()
                        .addGroup(panelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(nomCamp)
                            .addGroup(panelDatosClienteLayout.createSequentialGroup()
                                .addComponent(idCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(bttBuscarCliente)
                                .addGap(82, 82, 82)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelDatosClienteLayout.createSequentialGroup()
                        .addGroup(panelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(telfClient)
                            .addGroup(panelDatosClienteLayout.createSequentialGroup()
                                .addComponent(radConsumidorFinal)
                                .addGap(40, 40, 40)
                                .addComponent(radIngresarDatos))
                            .addComponent(emailCamp, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombresCliente)
                            .addComponent(emailCliente)
                            .addComponent(idCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(direccionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelDatosClienteLayout.createSequentialGroup()
                        .addGroup(panelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(telefonoCamp)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDatosClienteLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(botAniadirCli))
                            .addGroup(panelDatosClienteLayout.createSequentialGroup()
                                .addComponent(dirCamp, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 2, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        panelDatosClienteLayout.setVerticalGroup(
            panelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosClienteLayout.createSequentialGroup()
                .addGroup(panelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radConsumidorFinal)
                    .addComponent(radIngresarDatos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(idCliente)
                .addGap(1, 1, 1)
                .addGroup(panelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttBuscarCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombresCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomCamp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(direccionCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dirCamp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailCamp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(telfClient, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(telefonoCamp, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botAniadirCli)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(231, 253, 234));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "2. Detalle del Pedido", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        bttCargPed.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bttCargPed.setText("CARGAR PEDIDO");
        bttCargPed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttCargPedActionPerformed(evt);
            }
        });

        panelTab.setBackground(new java.awt.Color(204, 255, 255));

        tablaPedido.setBackground(new java.awt.Color(204, 255, 255));
        tablaPedido.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        tablaPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cantidad", "Descripción", "P. Unitario", "Total"
            }
        ));
        panelTab.setViewportView(tablaPedido);

        textID.setText("ID:");

        idCamp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idCampActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panelTab, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(textID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(idCamp, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bttCargPed)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttCargPed)
                    .addComponent(textID)
                    .addComponent(idCamp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTab, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelResumFact.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "3. Resumen de Factura", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        apliProm.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        apliProm.setText("Aplicar Promoción");
        apliProm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apliPromActionPerformed(evt);
            }
        });

        laSubtotal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        laSubtotal.setText("SUBTOTAL:");

        lbDescuento.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbDescuento.setText("DESCUENTO:");

        lbIVA.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbIVA.setText("IVA 15%:");

        lbTotal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbTotal.setText("TOTAL:");

        valSubtotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        valSubtotal.setText("$0.00");
        valSubtotal.setToolTipText("");

        valDescuento.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        valDescuento.setText("-$0.00");

        valIVA.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        valIVA.setText("$0.00");

        valTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        valTotal.setText("$0.00");

        botCalTotal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botCalTotal.setText("Calcular Total");
        botCalTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botCalTotalActionPerformed(evt);
            }
        });

        botGenFact.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botGenFact.setText("Generar Factura");
        botGenFact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botGenFactActionPerformed(evt);
            }
        });

        jLabel10.setText("Pago");

        javax.swing.GroupLayout panelResumFactLayout = new javax.swing.GroupLayout(panelResumFact);
        panelResumFact.setLayout(panelResumFactLayout);
        panelResumFactLayout.setHorizontalGroup(
            panelResumFactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResumFactLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelResumFactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelResumFactLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(panelResumFactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelResumFactLayout.createSequentialGroup()
                                .addComponent(botGenFact)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10)
                                .addGap(116, 116, 116))
                            .addGroup(panelResumFactLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelResumFactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbIVA)
                                    .addComponent(lbTotal)
                                    .addComponent(laSubtotal)
                                    .addComponent(lbDescuento))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 216, Short.MAX_VALUE)
                                .addGroup(panelResumFactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(valTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(valIVA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(valSubtotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(valDescuento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelResumFactLayout.createSequentialGroup()
                        .addComponent(apliProm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelResumFactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fieldPago)
                            .addComponent(botCalTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(32, 32, 32))
        );
        panelResumFactLayout.setVerticalGroup(
            panelResumFactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResumFactLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelResumFactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apliProm)
                    .addComponent(botCalTotal))
                .addGroup(panelResumFactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelResumFactLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel12))
                    .addGroup(panelResumFactLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelResumFactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelResumFactLayout.createSequentialGroup()
                                .addGroup(panelResumFactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelResumFactLayout.createSequentialGroup()
                                        .addComponent(laSubtotal)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbDescuento))
                                    .addGroup(panelResumFactLayout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addComponent(lbIVA)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbTotal))
                            .addGroup(panelResumFactLayout.createSequentialGroup()
                                .addComponent(valSubtotal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(valDescuento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(valIVA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(valTotal)))))
                .addGroup(panelResumFactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelResumFactLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelResumFactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelResumFactLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botGenFact)
                        .addGap(16, 16, 16))))
        );

        javax.swing.GroupLayout PanelFacturaLayout = new javax.swing.GroupLayout(PanelFactura);
        PanelFactura.setLayout(PanelFacturaLayout);
        PanelFacturaLayout.setHorizontalGroup(
            PanelFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFacturaLayout.createSequentialGroup()
                .addGroup(PanelFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelFacturaLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(panelDatosCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelResumFact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(PanelFacturaLayout.createSequentialGroup()
                        .addGap(306, 306, 306)
                        .addComponent(titleFact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        PanelFacturaLayout.setVerticalGroup(
            PanelFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFacturaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleFact, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelFacturaLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelResumFact, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelDatosCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        titleFact.getAccessibleContext().setAccessibleName("");

        tabCajero.addTab("Generar Factura", PanelFactura);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(255, 255, 204));

        labelTotalFactura.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        labelTotalFactura.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTotalFactura.setText("$ 0.00");

        jLabel7.setText("Total Efectivo en las Facturas");

        campoTotalEfectivo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        campoTotalEfectivo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoTotalEfectivo.setText("0.00");
        campoTotalEfectivo.setToolTipText("");
        campoTotalEfectivo.setBorder(null);
        campoTotalEfectivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTotalEfectivoActionPerformed(evt);
            }
        });

        jLabel8.setText("Total obtenido en Caja");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel7))
                            .addComponent(labelTotalFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel8))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(campoTotalEfectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(campoTotalEfectivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTotalFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        botonCerrarCaja.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonCerrarCaja.setText("Cerrar Caja");
        botonCerrarCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarCajaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101)
                .addComponent(botonCerrarCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(112, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(botonCerrarCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)))
                .addGap(39, 39, 39))
        );

        tabCajero.addTab("Cerrar Caja", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(tabCajero, javax.swing.GroupLayout.DEFAULT_SIZE, 778, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabCajero)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonCerrarCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrarCajaActionPerformed
        
        tabCajero.setEnabled(false);
        // 1. Calcular el total del sistema
    if (totalCajaCalculado == -1.0) {
        totalCajaCalculado = gestorCaja.calcularTotalEfectivo();
        labelTotalFactura.setText(String.format(Locale.US, "$ %.2f", totalCajaCalculado));
    }

    // 2. Obtener el valor ingresado por el usuario
    double totalIngresado;
    try {
        totalIngresado = Double.parseDouble(campoTotalEfectivo.getText());
        if (totalIngresado < 0) throw new NumberFormatException();
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "El valor ingresado no es un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // 3. Llamar al gestor para verificar y GUARDAR el reporte
    ReporteCierreCaja reporte = gestorCaja.verificarEstadoCaja(totalIngresado, totalCajaCalculado);
    
    // 4. Analizar el resultado del reporte
    if (reporte.getEstado().equals("Balance")) {
        
        // --- CASO 1: ÉXITO ---
        JOptionPane.showMessageDialog(this,
                "¡Caja Cerrada!\n" +
                "Estado: Balanceado\n" +
                "ID de Reporte: " + reporte.getIdReporte(),
                "Balance Correcto",
                JOptionPane.INFORMATION_MESSAGE);
        
        loginDeOrigen.setVisible(true);
        loginDeOrigen.deshabilitarBotonCajero();
        //Cerrar Cajero
        dispose();
        
    } else {
        
        // --- CASO 2: DESCUADRE ---
        intentosCierreCaja--; // Quitar un intento

        if (intentosCierreCaja > 0) {
            
            // --- Aún quedan intentos ---
            JOptionPane.showMessageDialog(this,
                    "¡Descuadre Detectado!\n" +
                    "Estado: " + reporte.getEstado() + "\n" +
                    "Descuadre: " + String.format(Locale.US, "$ %.2f", reporte.getDescuadre()) + "\n\n" +
                    "Por favor, verifique e intente de nuevo.\n" +
                    "Intentos restantes: " + intentosCierreCaja,
                    "Descuadre de Caja",
                    JOptionPane.WARNING_MESSAGE);
        } else {
            
            // --- Se acabaron los intentos ---
            JOptionPane.showMessageDialog(this,
                    "Límite de intentos alcanzado.\n" +
                    "El reporte final se ha guardado como: " + reporte.getEstado() + "\n" +
                    "ID de Reporte: " + reporte.getIdReporte(),
                    "Cierre de Caja Forzado",
                    JOptionPane.ERROR_MESSAGE);
            
            // Resetear para un futuro cierre
            loginDeOrigen.setVisible(true);
            loginDeOrigen.deshabilitarBotonCajero();
            //Cerrar Cajero
            dispose();
        }
    }

    }//GEN-LAST:event_botonCerrarCajaActionPerformed
    
   
    
    private void campoTotalEfectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTotalEfectivoActionPerformed

    }//GEN-LAST:event_campoTotalEfectivoActionPerformed

    private void sabor2OpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sabor2OpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sabor2OpActionPerformed

    private void sabor1OpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sabor1OpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sabor1OpActionPerformed

    private void opcionNumBolasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionNumBolasActionPerformed
        numBolas = Integer.parseInt(evt.getActionCommand());
        switch  (numBolas){
            case 1:
            sabor2Op.setEnabled(false);
            sabor3Op.setEnabled(false);
            break;
            case 2:
            sabor2Op.setEnabled(true);
            sabor3Op.setEnabled(false);
            break;
            case 3:
            sabor2Op.setEnabled(true);
            sabor3Op.setEnabled(true);
        }

    }//GEN-LAST:event_opcionNumBolasActionPerformed

    private void botonAgregarHeladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarHeladoActionPerformed
        try {
            // --- 1. Validar seleccion de GUI ---
            if (grupoNumBolas.getSelection() == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "Por favor, seleccione el número de bolas.");
                return;
            }

            // --- 2. Obtener Recipiente ---
            TipoRecipiente tipoRecipiente = (TipoRecipiente) comboRecipiente.getSelectedItem();

            // --- 3. Obtener Sabores ---
            ArrayList<SaborHelado> saboresSeleccionados = new ArrayList<>();
            saboresSeleccionados.add((SaborHelado) sabor1Op.getSelectedItem());
            if (numBolas >= 2) {
                saboresSeleccionados.add((SaborHelado) sabor2Op.getSelectedItem());
            }
            if (numBolas == 3) {
                saboresSeleccionados.add((SaborHelado) sabor3Op.getSelectedItem());
            }

            // --- 4. Llamar al GESTOR ---
            boolean exito = gestorPedido.agregarHelado(tipoRecipiente, saboresSeleccionados);

            // --- 5. Actualizar GUI
            if (exito) {
                limpiarCamposHelado();
                actualizarComboHelados();
            }

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al agregar helado: " + e.getMessage());
        }
    }//GEN-LAST:event_botonAgregarHeladoActionPerformed

    private void botonRegistrarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarPedidoActionPerformed
        // 2. Crear el objeto Pedido
        Pedido nuevo = gestorPedido.registrarPedidoActual();

        // Si el gestor devuelve null se sale del proceso.
        if (nuevo == null) {
            JOptionPane.showMessageDialog(null, "Error al registrar el pedido.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        // 1. Crear el panel principal
        JPanel panel = new JPanel();
        panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS));
        panel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 20));

        // 2. TÍTULO
        JLabel titulo = new JLabel("Detalle del Pedido");
        titulo.setFont(new Font("Segoe UI", Font.BOLD, 24));
        titulo.setAlignmentX(Component.LEFT_ALIGNMENT);
        panel.add(titulo);
        panel.add(Box.createVerticalStrut(10));

        // 3. INFORMACIÓN GENERAL DEL PEDIDO
        JLabel lblId = new JLabel("Pedido N°: " + nuevo.getPedidoID());
        lblId.setFont(new Font("Segoe UI", Font.PLAIN, 16));
        lblId.setAlignmentX(Component.LEFT_ALIGNMENT);
        panel.add(lblId);

        JLabel lblEstado = new JLabel("Estado: " + nuevo.getEstado());
        lblEstado.setFont(new Font("Segoe UI", Font.PLAIN, 16));
        lblEstado.setAlignmentX(Component.LEFT_ALIGNMENT);
        panel.add(lblEstado);
        panel.add(Box.createVerticalStrut(15)); // Espacio

        // 4. DETALLE DEL PEDIDO
        JLabel lblPedidoTitulo = new JLabel("Contenido del Pedido (" + nuevo.getHelados().size() + " helado(s)):");
        lblPedidoTitulo.setFont(new Font("Segoe UI", Font.BOLD, 18));
        lblPedidoTitulo.setAlignmentX(Component.LEFT_ALIGNMENT);
        panel.add(lblPedidoTitulo);

        if (nuevo.getHelados().isEmpty()) {
             JLabel lblItem = new JLabel("(Este pedido no tiene helados)");
             lblItem.setFont(new Font("Segoe UI", Font.ITALIC, 15)); // Itálica para "vacío"
             lblItem.setAlignmentX(Component.LEFT_ALIGNMENT);
             panel.add(lblItem);
        } else {
            for (Helado helado : nuevo.getHelados()) {
                JLabel lblItem = new JLabel("• " + helado.toString()); 
                lblItem.setFont(new Font("Segoe UI", Font.PLAIN, 15));
                lblItem.setAlignmentX(Component.LEFT_ALIGNMENT);
                panel.add(lblItem);
            }
        }


        // 5. SCROLL Y DIÁLOGO
        JScrollPane scroll = new JScrollPane(panel);
        JOptionPane.showMessageDialog(
                null,
                scroll,
                "Pedido N° " + nuevo.getPedidoID(), // Título de la ventana
                JOptionPane.INFORMATION_MESSAGE
        );

        labelNumPedido.setText(String.format("# %d", Pedido.getSiguienteNumPedido()));
        actualizarComboHelados();

    }//GEN-LAST:event_botonRegistrarPedidoActionPerformed

    private void comboHeladosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboHeladosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboHeladosActionPerformed

    private void botonEliminarHeladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarHeladoActionPerformed

        int indiceSeleccionado = comboHelados.getSelectedIndex();

        if (indiceSeleccionado == -1) {
            JOptionPane.showMessageDialog(this,
                    "No hay ningún helado seleccionado para eliminar.",
                    "Error",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        // --- 1. Llamar al GESTOR ---
        gestorPedido.eliminarHelado(indiceSeleccionado);

        // --- 2. Actualizar lista visible en la GUI ---
        actualizarComboHelados();
        limpiarCamposHelado();
    
    }//GEN-LAST:event_botonEliminarHeladoActionPerformed

    private void bttCargPedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttCargPedActionPerformed
        try {
            // --- 1. OBTENER Y VALIDAR EL ID DEL CAMPO DE TEXTO ---
            String idTexto = idCamp.getText().trim();
            int pedidoID;

            // Validamos que no esté vacío
            if (idTexto.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Por favor, ingrese un Número de Pedido.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Validamos que sea un número
            try {
                pedidoID = Integer.parseInt(idTexto);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "El Número de Pedido debe ser un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // --- 2. USAR EL GESTOR PARA BUSCAR ESE ID ---
            Pedido pedidoACargar = this.gestorPedido.buscarPedido(pedidoID);

            // 3. Validar que el gestor lo haya encontrado
            if (pedidoACargar == null) {
                JOptionPane.showMessageDialog(this, "No se encontró ningún pedido con el ID: " + pedidoID, "Pedido no Encontrado", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // --- 4. ¡GUARDAR EL PEDIDO PARA USARLO DESPUÉS! ---
            this.pedidoActualParaFacturar = pedidoACargar;
            
            JOptionPane.showMessageDialog(null,pedidoACargar.toString());
            
            // 5. Obtener el "modelo" de la tabla
            javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tablaPedido.getModel();
            model.setRowCount(0); // Limpiar

            // 6. Llenar la tabla
            for (Helado helado : this.pedidoActualParaFacturar.getHelados()) {
                int cantidad = 1;
                String descripcion = helado.toString();
                double pUnitario = helado.getPrecio();
                double total = pUnitario * cantidad;

                model.addRow(new Object[]{cantidad, descripcion, pUnitario, total});
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error inesperado al cargar el pedido.", "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_bttCargPedActionPerformed

    private void bttBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttBuscarClienteActionPerformed
        String cedula = idCampo.getText().trim(); // .trim() quita espacios en blanco

        // 1. Validación simple de la UI
        if (cedula.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese una cédula para buscar.", "Campo Vacío", JOptionPane.WARNING_MESSAGE);
            return;
        } else if(cedula.equals("9999999999")) {
            JOptionPane.showMessageDialog(this, "No se puede modificar ni eliminar a CONSUMIDOR FINAL.", "Campo Vacío", JOptionPane.ERROR_MESSAGE);
        }

        Cliente clienteEncontrado = this.gestorCliente.buscarCliente(cedula);

        if (clienteEncontrado != null) {
            // --- CLIENTE ENCONTRADO ---
            nomCamp.setText(clienteEncontrado.getNombre());
            dirCamp.setText(clienteEncontrado.getDireccion());
            emailCamp.setText(clienteEncontrado.getCorreoElectronico());
            telefonoCamp.setText(clienteEncontrado.getTelefono());

            telefonoCamp.setForeground(Color.BLACK);

            // 3. Deshabilitar campos
            nomCamp.setEnabled(false);
            dirCamp.setEnabled(false);
            emailCamp.setEnabled(false);
            telefonoCamp.setEnabled(false);
            botAniadirCli.setEnabled(false);

        } else {
            // --- CLIENTE NO ENCONTRADO ---

            // 2. Habilitar TODOS los campos
            nomCamp.setEnabled(true);
            dirCamp.setEnabled(true);
            emailCamp.setEnabled(true);
            telefonoCamp.setEnabled(true);

            // 3. Habilitar el botón "AÑADIR CLIENTE"
            botAniadirCli.setEnabled(true);

            // 4. Limpiar campos
            nomCamp.setText("");
            dirCamp.setText("");
            emailCamp.setText("");
            telefonoCamp.setText("");
        }
    }//GEN-LAST:event_bttBuscarClienteActionPerformed

    private void telefonoCampActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonoCampActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonoCampActionPerformed

    private void emailCampActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailCampActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailCampActionPerformed

    private void dirCampActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dirCampActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dirCampActionPerformed

    private void idCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idCampoActionPerformed

    private void radConsumidorFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radConsumidorFinalActionPerformed
        // 1. LLAMAMOS AL GESTOR
        Cliente cf = this.gestorCliente.buscarCliente("9999999999");

        if (cf != null) {
            // 2. Rellenar los campos
            idCampo.setText(cf.getCedula());
            nomCamp.setText(cf.getNombre());
            dirCamp.setText(cf.getDireccion());
            emailCamp.setText(cf.getCorreoElectronico());

            telefonoCamp.setText(cf.getTelefono());

            // Asegurarse de que el texto no sea gris
            idCampo.setForeground(Color.BLACK);
            nomCamp.setForeground(Color.BLACK);
            dirCamp.setForeground(Color.BLACK);
            emailCamp.setForeground(Color.BLACK);
            telefonoCamp.setForeground(Color.BLACK);

        } else {
            JOptionPane.showMessageDialog(this, "Error: No se pudo encontrar al Cliente 'Consumidor Final'", "Error de Gestor", JOptionPane.ERROR_MESSAGE);
        }

        // 3. Deshabilitar todos los campos y botones
        idCampo.setEnabled(false);
        nomCamp.setEnabled(false);
        dirCamp.setEnabled(false);
        emailCamp.setEnabled(false);
        telefonoCamp.setEnabled(false);
        bttBuscarCliente.setEnabled(false);
        botAniadirCli.setEnabled(false);
    }//GEN-LAST:event_radConsumidorFinalActionPerformed

    private void apliPromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apliPromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apliPromActionPerformed

    private void botAniadirCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botAniadirCliActionPerformed
        try {
            // --- 1. OBTENER Y LIMPIAR LOS DATOS ---
            String cedula = idCampo.getText().trim();
            if (cedula.equals("Ej. 1315267891")) cedula = "";

            String nombre = nomCamp.getText().trim();
            if (nombre.equals("Ej. Maria Lopez")) nombre = "";

            String direccion = dirCamp.getText().trim();
            if (direccion.equals("Ej. Av. Amazonas OE1") || direccion.isEmpty()) {
                direccion = "N/A"; // Valor por defecto si está vacío
            }

            String email = emailCamp.getText().trim();
            if (email.equals("Ej. marialope1@gmail.com")) email = "";

            String telefono = telefonoCamp.getText().trim();
            if (telefono.equals("Ej. 0965742142") || telefono.isEmpty()) {
                telefono = "N/A"; // Valor por defecto si está vacío
            }

            // --- 2. LLAMAR AL GESTOR ---
            boolean exito = this.gestorCliente.registrarCliente(nombre, cedula, email, direccion, telefono);

            // --- 3. ÉXITO ---
            if (exito) {
                // Deshabilitar cambios de la UI
                nomCamp.setEnabled(false);
                dirCamp.setEnabled(false);
                emailCamp.setEnabled(false);
                telefonoCamp.setEnabled(false);
                botAniadirCli.setEnabled(false);
            }
        } catch (Exception e) {
            // Error inesperado
            JOptionPane.showMessageDialog(this, "Ocurrió un error inesperado: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_botAniadirCliActionPerformed

    private void radIngresarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radIngresarDatosActionPerformed
        // 1. Habilitar SÓLO el ID y el botón Buscar
        idCampo.setEnabled(true);
        bttBuscarCliente.setEnabled(true);

        // 2. Limpiar todos los campos
        idCampo.setText("");
        nomCamp.setText("");
        dirCamp.setText("");
        emailCamp.setText("");
        telefonoCamp.setText("");

        // 3. Asegurarse de que el resto sigue deshabilitado
        nomCamp.setEnabled(false);
        dirCamp.setEnabled(false);
        emailCamp.setEnabled(false);
        telefonoCamp.setEnabled(false);
        botAniadirCli.setEnabled(false);
    }
    
    /**
     * Añade FocusListeners a los campos de texto para limpiar el texto gris de
     * ejemplo ("placeholder") cuando el usuario hace clic.
     */
    private void agregarListenersDePlaceholder() {
        // Campos de Cliente
        crearPlaceholder(idCampo, "Ej. 1315267891");
        crearPlaceholder(nomCamp, "Ej. Maria Lopez");
        crearPlaceholder(dirCamp, "Ej. Av. Amazonas OE1");
        crearPlaceholder(emailCamp, "Ej. marialope1@gmail.com");
        crearPlaceholder(telefonoCamp, "Ej. 0965742142");
    }

    /**
     * Método de utilidad para crear un efecto de placeholder.
     *
     * @param campo El JTextField
     * @param textoPlaceholder El texto gris de ejemplo
     */
    private void crearPlaceholder(javax.swing.JTextField campo, String textoPlaceholder) {
        // Color gris para el placeholder
        Color placeholderColor = new Color(204, 204, 204);
        // Color negro para el texto normal
        Color textColor = Color.BLACK;

        // Estado inicial
        if (campo.getText().isEmpty()) {
            campo.setText(textoPlaceholder);
            campo.setForeground(placeholderColor);
        }

        campo.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent e) {
                // Si el texto es el placeholder, borrarlo y poner color negro
                if (campo.getText().equals(textoPlaceholder)) {
                    campo.setText("");
                    campo.setForeground(textColor);
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent e) {
                // Si el campo está vacío, volver a poner el placeholder
                if (campo.getText().isEmpty()) {
                    campo.setText(textoPlaceholder);
                    campo.setForeground(placeholderColor);
                }
            }
        });
    }//GEN-LAST:event_radIngresarDatosActionPerformed

    private void botCalTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botCalTotalActionPerformed
        // 1. Validar que un pedido esté cargado
        if (this.pedidoActualParaFacturar == null) {
            JOptionPane.showMessageDialog(this, "Debe presionar 'CARGAR PEDIDO' primero.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 2. Obtener datos de la GUI
        int pedidoID = this.pedidoActualParaFacturar.getPedidoID();
        boolean aplicaPromocion = apliProm.isSelected();

        // 3. Llamar al GESTOR para que haga TODOS los cálculos
        Map<String, Double> totales = gestorFactura.calcularTotalesPedido(pedidoID, aplicaPromocion);

        // 4. Actualizar los JLabels con los resultados del Map
        valSubtotal.setText(String.format(Locale.US, "$%.2f", totales.get("subtotal")));
        valDescuento.setText(String.format(Locale.US, "-$%.2f", totales.get("descuento")));
        valIVA.setText(String.format(Locale.US, "$%.2f", totales.get("iva")));
        valTotal.setText(String.format(Locale.US, "$%.2f", totales.get("total")));
    }//GEN-LAST:event_botCalTotalActionPerformed

    private void botGenFactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botGenFactActionPerformed
        try {
            // --- 1. VALIDACIONES ---
            if (this.pedidoActualParaFacturar == null) {
                JOptionPane.showMessageDialog(this, "Debe presionar 'CARGAR PEDIDO' primero.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            if (this.pedidoActualParaFacturar.getEstado().equals("FACTURADO")){
            JOptionPane.showMessageDialog(this, "NO se puede emplear un pedido ya FACTURADO", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            if (valTotal.getText().equals("$0.00") || valTotal.getText().equals("$0.0")) {
                JOptionPane.showMessageDialog(this, "Debe presionar 'CALCULAR TOTAL' primero.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            String clienteCedula = idCampo.getText().trim();
            if (clienteCedula.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No se ha definido un cliente.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            double totalUI = Double.parseDouble(valTotal.getText().replace("$", ""));

            if(!gestorFactura.validarPago(fieldPago.getText(), totalUI)){
                return;
            }
            double pago = Double.parseDouble(fieldPago.getText());

            // --- 2. LLAMAR AL GESTOR PARA CREAR LA FACTURA ---
            // 1. Obtener la aprobacion de aplicar la promocion
            boolean aplicarPromocion = apliProm.isSelected();

            // 2. Se llama al gestor
                        Factura facturaGenerada = this.gestorFactura.generarFactura(
                                this.pedidoActualParaFacturar.getPedidoID(),
                                clienteCedula,
                                aplicarPromocion
                        );

            // 3. Verifica si la factura se creó
                        if (facturaGenerada == null) {
                            return;
                        }

            // 4. Asignar valores
            facturaGenerada.setTipoPago("EFECTIVO");
            facturaGenerada.setPago(pago);
            facturaGenerada.setCambio(gestorFactura.calcularCambio(totalUI, pago)); // O calcular el cambio

            // --- 4. MOSTRAR LA VENTANA DE FACTURA ---
            VentanaFactura factura = new VentanaFactura(this, true, facturaGenerada);
            factura.setVisible(true);

            // --- 5. LIMPIAR TODO PARA EL SIGUIENTE CLIENTE ---
            limpiarPestanaFactura();

        } catch (ClassCastException cce) {
            JOptionPane.showMessageDialog(this, "Error de Programación: Incompatibilidad de Gestores. " + cce.getMessage(), "Error Crítico", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error final al generar la factura: ", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botGenFactActionPerformed

    private void idCampActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idCampActionPerformed
        bttCargPed.doClick();
    }//GEN-LAST:event_idCampActionPerformed

    private void limpiarPestanaFactura() {
        // 1. Resetea el cliente a "Consumidor Final"
        radConsumidorFinal.setSelected(true);
        radConsumidorFinalActionPerformed(null);

        // 2. Limpia el campo de ID de Pedido
        idCamp.setText("");

        // 3. Limpia la tabla
        ((javax.swing.table.DefaultTableModel) tablaPedido.getModel()).setRowCount(0);

        // 4. Resetea el pedido guardado
        this.pedidoActualParaFacturar = null;

        // 5. Resetea el checkbox de promoción
        apliProm.setSelected(false);

        // 6. Resetea los totales
        valSubtotal.setText("$0.00");
        valDescuento.setText("-$0.00");
        valIVA.setText("$0.00");
        valTotal.setText("$0.00");

        // 7. Vuelve a poner el texto de ejemplo (placeholder)
        agregarListenersDePlaceholder();
    }
    
    private void limpiarCamposHelado() {
    grupoNumBolas.clearSelection(); // Des-selecciona los radio buttons
    comboRecipiente.setSelectedIndex(0);
    sabor1Op.setSelectedIndex(0);
    sabor2Op.setSelectedIndex(0);
    sabor3Op.setSelectedIndex(0);
    
    // Vuelve a deshabilitar los combos 2 y 3
    sabor2Op.setEnabled(false);
    sabor3Op.setEnabled(false);
    }
    
    private void actualizarComboHelados() {
    // 1. Limpiar Lista
    comboHelados.removeAllItems();

    // 2. Recorrer la lista de helados del pedido actual
    for (Helado helado : this.gestorPedido.getHeladosDelPedidoActual()) {
        comboHelados.addItem(helado);
    }
}


    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelFactura;
    private javax.swing.JCheckBox apliProm;
    private javax.swing.JButton botAniadirCli;
    private javax.swing.JButton botCalTotal;
    private javax.swing.JButton botGenFact;
    private javax.swing.JButton botonAgregarHelado;
    private javax.swing.JButton botonCerrarCaja;
    private javax.swing.JButton botonEliminarHelado;
    private javax.swing.JButton botonRegistrarPedido;
    private javax.swing.JButton bttBuscarCliente;
    private javax.swing.JButton bttCargPed;
    private javax.swing.ButtonGroup buttonSelecCliente;
    private javax.swing.JTextField campoTotalEfectivo;
    private javax.swing.JComboBox<Helado> comboHelados;
    private javax.swing.JComboBox<TipoRecipiente> comboRecipiente;
    private javax.swing.JTextField dirCamp;
    private javax.swing.JLabel direccionCliente;
    private javax.swing.JTextField emailCamp;
    private javax.swing.JLabel emailCliente;
    private javax.swing.JTextField fieldPago;
    private javax.swing.ButtonGroup grupoNumBolas;
    private javax.swing.JTextField idCamp;
    private javax.swing.JTextField idCampo;
    private javax.swing.JLabel idCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel laSubtotal;
    private javax.swing.JLabel labelNumPedido;
    private javax.swing.JLabel labelTotalFactura;
    private javax.swing.JLabel lbDescuento;
    private javax.swing.JLabel lbIVA;
    private javax.swing.JLabel lbTotal;
    private javax.swing.JTextField nomCamp;
    private javax.swing.JLabel nombresCliente;
    private javax.swing.JRadioButton opcionDos;
    private javax.swing.JRadioButton opcionTres;
    private javax.swing.JRadioButton opcionUna;
    private javax.swing.JPanel panelDatosCliente;
    private javax.swing.JPanel panelResumFact;
    private javax.swing.JScrollPane panelTab;
    private javax.swing.JRadioButton radConsumidorFinal;
    private javax.swing.JRadioButton radIngresarDatos;
    private javax.swing.JComboBox<SaborHelado> sabor1Op;
    private javax.swing.JComboBox<SaborHelado> sabor2Op;
    private javax.swing.JComboBox<SaborHelado> sabor3Op;
    private javax.swing.JTabbedPane tabCajero;
    private javax.swing.JTable tablaPedido;
    private javax.swing.JTextField telefonoCamp;
    private javax.swing.JLabel telfClient;
    private javax.swing.JLabel textID;
    private javax.swing.JPanel titleFact;
    private javax.swing.JLabel valDescuento;
    private javax.swing.JLabel valIVA;
    private javax.swing.JLabel valSubtotal;
    private javax.swing.JLabel valTotal;
    // End of variables declaration//GEN-END:variables
}
